# -*- cmake -*-

# - Find GPerfTools (formerly Google perftools)
# Find the GPerfTools libraries
# If false, do not try to use Google perftools.
# also defined for general use are
#  TCMALLOC_LIBRARY, where to find the tcmalloc library.

SET(TCMALLOC_NAMES ${TCMALLOC_NAMES} tcmalloc)
find_library(TCMALLOC_LIBRARY
  NAMES ${TCMALLOC_NAMES}
  PATHS /usr/lib /usr/local/lib
)
find_library(GPERFTOOLS_PROFILER
   NAMES profiler
   PATHS /usr/lib /usr/local/lib
)

IF (TCMALLOC_LIBRARY AND GPERFTOOLS_PROFILER)
    SET(TCMALLOC_LIBRARIES ${TCMALLOC_LIBRARY})
    SET(GOOGLE_PERFTOOLS_FOUND "YES")
ELSE (TCMALLOC_LIBRARY AND GPERFTOOLS_PROFILER)
  SET(GOOGLE_PERFTOOLS_FOUND "NO")
ENDIF (TCMALLOC_LIBRARY AND GPERFTOOLS_PROFILER)

IF (GOOGLE_PERFTOOLS_FOUND)
   MESSAGE(STATUS "Found Google perftools: ${GPERFTOOLS_PROFILER}")
ELSE (GOOGLE_PERFTOOLS_FOUND)
   IF (GOOGLE_PERFTOOLS_FIND_REQUIRED)
      MESSAGE(FATAL_ERROR "Could not find Google perftools library")
   ENDIF (GOOGLE_PERFTOOLS_FIND_REQUIRED)
ENDIF (GOOGLE_PERFTOOLS_FOUND)

MARK_AS_ADVANCED(
  TCMALLOC_LIBRARY
  GPERFTOOLS_PROFILER
)
